test: demo1 demo2 demo3 demo4

demo1: demo1.c memlab.c
	gcc memlab.c demo1.c -o demo1 -lpthread

demo2: demo2.c memlab.c
	gcc memlab.c demo2.c -o demo2 -lpthread

demo3: demo3.c memlab.c
	gcc memlab.c demo3.c -o demo3 -lpthread

demo4: demo4.c memlab.c
	gcc memlab.c demo4.c -o demo4 -lpthread

clean:
	rm demo1 demo2 demo3 demo4